case ERROR_ACCESS_DENIED: return EACCES;
/* case ERROR_ACCOUNT_DISABLED: return E; */
/* case ERROR_ACCOUNT_EXPIRED: return E; */
/* case ERROR_ACCOUNT_LOCKED_OUT: return E; */
/* case ERROR_ACCOUNT_RESTRICTION: return E; */
/* case ERROR_ACTIVE_CONNECTIONS: return E; */
/* case ERROR_ADAP_HDW_ERR: return E; */
case ERROR_ADDRESS_ALREADY_ASSOCIATED: return EBUSY;
/* case ERROR_ADDRESS_NOT_ASSOCIATED: return E; */
/* case ERROR_ALIAS_EXISTS: return E; */
/* case ERROR_ALLOTTED_SPACE_EXCEEDED: return E; */
/* case ERROR_ALREADY_ASSIGNED: return E; */
case ERROR_ALREADY_EXISTS: return EEXIST;
/* case ERROR_ALREADY_INITIALIZED: return E; */
/* case ERROR_ALREADY_REGISTERED: return E; */
/* case ERROR_ALREADY_RUNNING_LKG: return E; */
/* case ERROR_ALREADY_WAITING: return E; */
/* case ERROR_APP_WRONG_OS: return E; */
/* case ERROR_ARENA_TRASHED: return E; */
/* case ERROR_ARITHMETIC_OVERFLOW: return E; */
/* case ERROR_ATOMIC_LOCKS_NOT_SUPPORTED: return E; */
/* case ERROR_AUTODATASEG_EXCEEDS_64k: return E; */
case ERROR_BAD_ARGUMENTS: return EINVAL;
/* case ERROR_BAD_COMMAND: return E; */
/* case ERROR_BAD_DESCRIPTOR_FORMAT: return E; */
/* case ERROR_BAD_DEV_TYPE: return E; */
/* case ERROR_BAD_DEVICE: return E; */
/* case ERROR_BAD_DRIVER: return E; */
/* case ERROR_BAD_DRIVER_LEVEL: return E; */
/* case ERROR_BAD_ENVIRONMENT: return E; */
/* case ERROR_BAD_EXE_FORMAT: return E; */
/* case ERROR_BAD_FORMAT: return E; */
/* case ERROR_BAD_IMPERSONATION_LEVEL: return E; */
/* case ERROR_BAD_INHERITANCE_ACL: return E; */
/* case ERROR_BAD_LENGTH: return E; */
/* case ERROR_BAD_LOGON_SESSION_STATE: return E; */
/* case ERROR_BAD_NET_NAME: return E; */
/* case ERROR_BAD_NET_RESP: return E; */
/* case ERROR_BAD_NETPATH: return E; */
/* case ERROR_BAD_PATHNAME: return E; */
/* case ERROR_BAD_PIPE: return E; */
/* case ERROR_BAD_PROFILE: return E; */
/* case ERROR_BAD_PROVIDER: return E; */
/* case ERROR_BAD_REM_ADAP: return E; */
/* case ERROR_BAD_THREADID_ADDR: return E; */
/* case ERROR_BAD_TOKEN_TYPE: return E; */
/* case ERROR_BAD_UNIT: return E; */
/* case ERROR_BAD_USERNAME: return E; */
/* case ERROR_BAD_VALIDATION_CLASS: return E; */
/* case ERROR_BADDB: return E; */
/* case ERROR_BADKEY: return E; */
/* case ERROR_BEGINNING_OF_MEDIA: return E; */
/* case ERROR_BOOT_ALREADY_ACCEPTED: return E; */
case ERROR_BROKEN_PIPE: return EPIPE;
/* case ERROR_BUFFER_OVERFLOW: return E; */
/* case ERROR_BUS_RESET: return E; */
case ERROR_BUSY: return EBUSY;
/* case ERROR_BUSY_DRIVE: return E; */
/* case ERROR_CALL_NOT_IMPLEMENTED: return E; */
/* case ERROR_CAN_NOT_COMPLETE: return E; */
/* case ERROR_CAN_NOT_DEL_LOCAL_WINS: return E; */
/* case ERROR_CANCEL_VIOLATION: return E; */
/* case ERROR_CANCELLED: return E; */
/* case ERROR_CANNOT_COPY: return E; */
/* case ERROR_CANNOT_FIND_WND_CLASS: return E; */
/* case ERROR_CANNOT_IMPERSONATE: return E; */
/* case ERROR_CANNOT_MAKE: return E; */
/* case ERROR_CANNOT_OPEN_PROFILE: return E; */
/* case ERROR_CANT_ACCESS_DOMAIN_INFO: return E; */
/* case ERROR_CANT_DISABLE_MANDATORY: return E; */
/* case ERROR_CANT_OPEN_ANONYMOUS: return E; */
/* case ERROR_CANTOPEN: return E; */
/* case ERROR_CANTREAD: return E; */
/* case ERROR_CANTWRITE: return E; */
/* case ERROR_CHILD_MUST_BE_VOLATILE: return E; */
/* case ERROR_CHILD_NOT_COMPLETE: return E; */
/* case ERROR_CHILD_WINDOW_MENU: return E; */
/* case ERROR_CIRCULAR_DEPENDENCY: return E; */
/* case ERROR_CLASS_ALREADY_EXISTS: return E; */
/* case ERROR_CLASS_DOES_NOT_EXIST: return E; */
/* case ERROR_CLASS_HAS_WINDOWS: return E; */
/* case ERROR_CLIPBOARD_NOT_OPEN: return E; */
/* case ERROR_CLIPPING_NOT_SUPPORTED: return E; */
/* case ERROR_COMMITMENT_LIMIT: return E; */
/* case ERROR_CONNECTION_ABORTED: return E; */
/* case ERROR_CONNECTION_ACTIVE: return E; */
/* case ERROR_CONNECTION_COUNT_LIMIT: return E; */
/* case ERROR_CONNECTION_INVALID: return E; */
/* case ERROR_CONNECTION_REFUSED: return E; */
/* case ERROR_CONNECTION_UNAVAIL: return E; */
/* case ERROR_CONTINUE: return E; */
/* case ERROR_CONTROL_ID_NOT_FOUND: return E; */
/* case ERROR_COUNTER_TIMEOUT: return E; */
/* case ERROR_CRC: return E; */
/* case ERROR_CURRENT_DIRECTORY: return E; */
/* case ERROR_DATABASE_DOES_NOT_EXIST: return E; */
/* case ERROR_DC_NOT_FOUND: return E; */
/* case ERROR_DDE_FAIL: return E; */
/* case ERROR_DEPENDENT_SERVICES_RUNNING: return E; */
/* case ERROR_DESTROY_OBJECT_OF_OTHER_THREAD: return E; */
/* case ERROR_DEV_NOT_EXIST: return E; */
/* case ERROR_DEVICE_ALREADY_REMEMBERED: return E; */
/* case ERROR_DEVICE_IN_USE: return E; */
/* case ERROR_DEVICE_NOT_PARTITIONED: return E; */
/* case ERROR_DIFFERENT_SERVICE_ACCOUNT: return E; */
/* case ERROR_DIR_NOT_EMPTY: return E; */
/* case ERROR_DIR_NOT_ROOT: return E; */
/* case ERROR_DIRECT_ACCESS_HANDLE: return E; */
/* case ERROR_DIRECTORY: return E; */
/* case ERROR_DISCARDED: return E; */
/* case ERROR_DISK_CHANGE: return E; */
/* case ERROR_DISK_CORRUPT: return E; */
case ERROR_DISK_FULL: return ENOSPC;
case ERROR_DISK_OPERATION_FAILED: return EIO;
case ERROR_DISK_RECALIBRATE_FAILED: return EIO;
case ERROR_DISK_RESET_FAILED: return EIO;
/* case ERROR_DLL_INIT_FAILED: return E; */
/* case ERROR_DLL_NOT_FOUND: return E; */
/* case ERROR_DOMAIN_CONTROLLER_NOT_FOUND: return E; */
/* case ERROR_DOMAIN_EXISTS: return E; */
/* case ERROR_DOMAIN_LIMIT_EXCEEDED: return E; */
/* case ERROR_DOMAIN_TRUST_INCONSISTENT: return E; */
/* case ERROR_DRIVE_LOCKED: return E; */
/* case ERROR_DUP_DOMAINNAME: return E; */
/* case ERROR_DUP_NAME: return E; */
/* case ERROR_DUPLICATE_SERVICE_NAME: return E; */
/* case ERROR_DYNLINK_FROM_INVALID_RING: return E; */
/* case ERROR_EA_ACCESS_DENIED: return E; */
/* case ERROR_EA_FILE_CORRUPT: return E; */
/* case ERROR_EA_LIST_INCONSISTENT: return E; */
/* case ERROR_EA_TABLE_FULL: return E; */
/* case ERROR_EAS_DIDNT_FIT: return E; */
/* case ERROR_EAS_NOT_SUPPORTED: return E; */
/* case ERROR_END_OF_MEDIA: return E; */
/* case ERROR_ENVVAR_NOT_FOUND: return E; */
/* case ERROR_EOM_OVERFLOW: return E; */
/* case ERROR_EVENTLOG_CANT_START: return E; */
/* case ERROR_EVENTLOG_FILE_CHANGED: return E; */
/* case ERROR_EVENTLOG_FILE_CORRUPT: return E; */
/* case ERROR_EXCEPTION_IN_SERVICE: return E; */
/* case ERROR_EXCL_SEM_ALREADY_OWNED: return E; */
/* case ERROR_EXE_MARKED_INVALID: return E; */
/* case ERROR_EXTENDED_ERROR: return E; */
/* case ERROR_FAIL_I24: return E; */
/* case ERROR_FAILED_SERVICE_CONTROLLER_CONNECT: return E; */
/* case ERROR_FILE_CORRUPT: return E; */
case ERROR_FILE_EXISTS: return EEXIST;
/* case ERROR_FILE_INVALID: return E; */
case ERROR_FILE_NOT_FOUND: return ENOENT;
/* case ERROR_FILEMARK_DETECTED: return E; */
/* case ERROR_FILENAME_EXCED_RANGE: return E; */
/* case ERROR_FLOPPY_BAD_REGISTERS: return E; */
/* case ERROR_FLOPPY_ID_MARK_NOT_FOUND: return E; */
/* case ERROR_FLOPPY_WRONG_CYLINDER: return E; */
/* case ERROR_FLOPPY_UNKNOWN_ERROR: return E; */
/* case ERROR_FULL_BACKUP: return E; */
/* case ERROR_FULLSCREEN_MODE: return E; */
/* case ERROR_GEN_FAILURE: return E; */
/* case ERROR_GENERIC_NOT_MAPPED: return E; */
/* case ERROR_GLOBAL_ONLY_HOOK: return E; */
/* case ERROR_GRACEFUL_DISCONNECT: return E; */
/* case ERROR_GROUP_EXISTS: return E; */
/* case ERROR_HANDLE_DISK_FULL: return E; */
/* case ERROR_HANDLE_EOF: return E; */
/* case ERROR_HOOK_NEEDS_HMOD: return E; */
/* case ERROR_HOOK_NOT_INSTALLED: return E; */
/* case ERROR_HOOK_TYPE_NOT_ALLOWED: return E; */
/* case ERROR_HOST_UNREACHABLE: return E; */
/* case ERROR_HOTKEY_ALREADY_REGISTERED: return E; */
/* case ERROR_HOTKEY_NOT_REGISTERED: return E; */
/* case ERROR_HWNDS_HAVE_DIFFERENT_PARENT: return E; */
/* case ERROR_ILL_FORMED_PASSWORD: return E; */
/* case ERROR_INC_BACKUP: return E; */
/* case ERROR_INCORRECT_ADDRESS: return E; */
/* case ERROR_INFLOOP_IN_RELOC_CHAIN: return E; */
/* case ERROR_INSUFFICIENT_BUFFER: return E; */
/* case ERROR_INTERNAL_DB_CORRUPTION: return E; */
/* case ERROR_INTERNAL_DB_ERROR: return E; */
/* case ERROR_INTERNAL_ERROR: return E; */
/* case ERROR_INVALID_ACCEL_HANDLE: return E; */
/* case ERROR_INVALID_ACCESS: return E; */
/* case ERROR_INVALID_ACCOUNT_NAME: return E; */
/* case ERROR_INVALID_ACL: return E; */
/* case ERROR_INVALID_ADDRESS: return E; */
/* case ERROR_INVALID_AT_INTERRUPT_TIME: return E; */
/* case ERROR_INVALID_BLOCK: return E; */
/* case ERROR_INVALID_BLOCK_LENGTH: return E; */
/* case ERROR_INVALID_CATEGORY: return E; */
/* case ERROR_INVALID_COMBOBOX_MESSAGE: return E; */
/* case ERROR_INVALID_COMPUTERNAME: return E; */
/* case ERROR_INVALID_CURSOR_HANDLE: return E; */
/* case ERROR_INVALID_DATA: return E; */
/* case ERROR_INVALID_DATATYPE: return E; */
/* case ERROR_INVALID_DLL: return E; */
/* case ERROR_INVALID_DOMAINNAME: return E; */
/* case ERROR_INVALID_DOMAIN_ROLE: return E; */
/* case ERROR_INVALID_DOMAIN_STATE: return E; */
/* case ERROR_INVALID_DRIVE: return E; */
/* case ERROR_INVALID_DWP_HANDLE: return E; */
/* case ERROR_INVALID_EA_HANDLE: return E; */
/* case ERROR_INVALID_EA_NAME: return E; */
/* case ERROR_INVALID_EDIT_HEIGHT: return E; */
/* case ERROR_INVALID_ENVIRONMENT: return E; */
/* case ERROR_INVALID_EVENT_COUNT: return E; */
/* case ERROR_INVALID_EVENTNAME: return E; */
/* case ERROR_INVALID_EXE_SIGNATURE: return E; */
/* case ERROR_INVALID_FILTER_PROC: return E; */
/* case ERROR_INVALID_FLAG_NUMBER: return E; */
/* case ERROR_INVALID_FLAGS: return E; */
/* case ERROR_INVALID_FUNCTION: return E; */
/* case ERROR_INVALID_GROUP_ATTRIBUTES: return E; */
/* case ERROR_INVALID_GROUPNAME: return E; */
/* case ERROR_INVALID_GW_COMMAND: return E; */
/* case ERROR_INVALID_FORM_NAME: return E; */
/* case ERROR_INVALID_FORM_SIZE: return E; */
case ERROR_INVALID_HANDLE: return EBADF;
/* case ERROR_INVALID_HOOK_FILTER: return E; */
/* case ERROR_INVALID_HOOK_HANDLE: return E; */
/* case ERROR_INVALID_ICON_HANDLE: return E; */
/* case ERROR_INVALID_ID_AUTHORITY: return E; */
/* case ERROR_INVALID_INDEX: return E; */
/* case ERROR_INVALID_KEYBOARD_HANDLE: return E; */
/* case ERROR_INVALID_LB_MESSAGE: return E; */
/* case ERROR_INVALID_LEVEL: return E; */
/* case ERROR_INVALID_LIST_FORMAT: return E; */
/* case ERROR_INVALID_LOGON_HOURS: return E; */
/* case ERROR_INVALID_LOGON_TYPE: return E; */
/* case ERROR_INVALID_MEMBER: return E; */
/* case ERROR_INVALID_MENU_HANDLE: return E; */
/* case ERROR_INVALID_MESSAGE: return E; */
/* case ERROR_INVALID_MESSAGEDEST: return E; */
/* case ERROR_INVALID_MESSAGENAME: return E; */
/* case ERROR_INVALID_MINALLOCSIZE: return E; */
/* case ERROR_INVALID_MODULETYPE: return E; */
/* case ERROR_INVALID_MSGBOX_STYLE: return E; */
/* case ERROR_INVALID_NAME: return E; */
/* case ERROR_INVALID_NETNAME: return E; */
/* case ERROR_INVALID_ORDINAL: return E; */
/* case ERROR_INVALID_OWNER: return E; */
case ERROR_INVALID_PARAMETER: return EINVAL;
/* case ERROR_INVALID_PASSWORD: return E; */
/* case ERROR_INVALID_PASSWORDNAME: return E; */
/* case ERROR_INVALID_PIXEL_FORMAT: return E; */
/* case ERROR_INVALID_PRIMARY_GROUP: return E; */
/* case ERROR_INVALID_PRINT_MONITOR: return E; */
/* case ERROR_INVALID_PRINTER_COMMAND: return E; */
/* case ERROR_INVALID_PRINTER_NAME: return E; */
/* case ERROR_INVALID_PRINTER_STATE: return E; */
/* case ERROR_INVALID_PRIORITY: return E; */
/* case ERROR_INVALID_SCROLLBAR_RANGE: return E; */
/* case ERROR_INVALID_SECURITY_DESCR: return E; */
/* case ERROR_INVALID_SEGDPL: return E; */
/* case ERROR_INVALID_SEGMENT_NUMBER: return E; */
/* case ERROR_INVALID_SEPARATOR_FILE: return E; */
/* case ERROR_INVALID_SERVER_STATE: return E; */
/* case ERROR_INVALID_SERVICE_ACCOUNT: return E; */
/* case ERROR_INVALID_SERVICE_CONTROL: return E; */
/* case ERROR_INVALID_SERVICE_LOCK: return E; */
/* case ERROR_INVALID_SERVICENAME: return E; */
/* case ERROR_INVALID_SHARENAME: return E; */
/* case ERROR_INVALID_SHOWWIN_COMMAND: return E; */
/* case ERROR_INVALID_SID: return E; */
/* case ERROR_INVALID_SIGNAL_NUMBER: return E; */
/* case ERROR_INVALID_SPI_VALUE: return E; */
/* case ERROR_INVALID_STACKSEG: return E; */
/* case ERROR_INVALID_STARTING_CODESEG: return E; */
/* case ERROR_INVALID_SUB_AUTHORITY: return E; */
/* case ERROR_INVALID_TARGET_HANDLE: return E; */
/* case ERROR_INVALID_THREAD_ID: return E; */
/* case ERROR_INVALID_TIME: return E; */
case ERROR_INVALID_USER_BUFFER: return ENOMEM;
/* case ERROR_INVALID_VERIFY_SWITCH: return E; */
/* case ERROR_INVALID_WINDOW_HANDLE: return E; */
/* case ERROR_INVALID_WINDOW_STYLE: return E; */
/* case ERROR_INVALID_WORKSTATION: return E; */
/* case ERROR_IO_DEVICE: return E; */
/* case ERROR_IO_INCOMPLETE: return E; */
/* case ERROR_IO_PENDING: return E; */
/* case ERROR_IOPL_NOT_ENABLED: return E; */
/* case ERROR_IRQ_BUSY: return E; */
/* case ERROR_IS_JOIN_PATH: return E; */
/* case ERROR_IS_JOIN_TARGET: return E; */
/* case ERROR_IS_JOINED: return E; */
/* case ERROR_IS_SUBST_PATH: return E; */
/* case ERROR_IS_SUBST_TARGET: return E; */
/* case ERROR_IS_SUBSTED: return E; */
/* case ERROR_ITERATED_DATA_EXCEEDS_64k: return E; */
/* case ERROR_JOIN_TO_JOIN: return E; */
/* case ERROR_JOIN_TO_SUBST: return E; */
/* case ERROR_JOURNAL_HOOK_SET: return E; */
/* case ERROR_KEY_DELETED: return E; */
/* case ERROR_KEY_HAS_CHILDREN: return E; */
/* case ERROR_LABEL_TOO_LONG: return E; */
/* case ERROR_LAST_ADMIN: return E; */
/* case ERROR_LB_WITHOUT_TABSTOPS: return E; */
/* case ERROR_LICENSE_QUOTA_EXCEEDED: return E; */
/* case ERROR_LISTBOX_ID_NOT_FOUND: return E; */
/* case ERROR_LM_CROSS_ENCRYPTION_REQUIRED: return E; */
/* case ERROR_LOCAL_USER_SESSION_KEY: return E; */
/* case ERROR_LOCK_FAILED: return E; */
/* case ERROR_LOCK_VIOLATION: return E; */
/* case ERROR_LOCKED: return E; */
/* case ERROR_LOG_FILE_FULL: return E; */
/* case ERROR_LOGIN_TIME_RESTRICTION: return E; */
/* case ERROR_LOGIN_WKSTA_RESTRICTION: return E; */
/* case ERROR_LOGON_FAILURE: return E; */
/* case ERROR_LOGON_NOT_GRANTED: return E; */
/* case ERROR_LOGON_SESSION_COLLISION: return E; */
/* case ERROR_LOGON_SESSION_EXISTS: return E; */
/* case ERROR_LOGON_TYPE_NOT_GRANTED: return E; */
/* case ERROR_LUIDS_EXHAUSTED: return E; */
/* case ERROR_MAPPED_ALIGNMENT: return E; */
/* case ERROR_MAX_THRDS_REACHED: return E; */
/* case ERROR_MEDIA_CHANGED: return E; */
/* case ERROR_MEMBER_IN_ALIAS: return E; */
/* case ERROR_MEMBER_IN_GROUP: return E; */
/* case ERROR_MEMBER_NOT_IN_ALIAS: return E; */
/* case ERROR_MEMBER_NOT_IN_GROUP: return E; */
/* case ERROR_MEMBERS_PRIMARY_GROUP: return E; */
/* case ERROR_MENU_ITEM_NOT_FOUND: return E; */
/* case ERROR_META_EXPANSION_TOO_LONG: return E; */
/* case ERROR_METAFILE_NOT_SUPPORTED: return E; */
/* case ERROR_MOD_NOT_FOUND: return E; */
/* case ERROR_MORE_DATA: return E; */
/* case ERROR_MORE_WRITES: return E; */
/* case ERROR_MR_MID_NOT_FOUND: return E; */
/* case ERROR_NEGATIVE_SEEK: return E; */
/* case ERROR_NESTING_NOT_ALLOWED: return E; */
/* case ERROR_NETLOGON_NOT_STARTED: return E; */
/* case ERROR_NET_WRITE_FAULT: return E; */
/* case ERROR_NETNAME_DELETED: return E; */
/* case ERROR_NETWORK_ACCESS_DENIED: return E; */
/* case ERROR_NETWORK_BUSY: return E; */
/* case ERROR_NETWORK_UNREACHABLE: return E; */
/* case ERROR_NO_ASSOCIATION: return E; */
/* case ERROR_NO_BROWSER_SERVERS_FOUND: return E; */
/* case ERROR_NO_DATA: return E; */
/* case ERROR_NO_DATA_DETECTED: return E; */
/* case ERROR_NO_IMPERSONATION_TOKEN: return E; */
/* case ERROR_NO_INHERITANCE: return E; */
/* case ERROR_NO_LOG_SPACE: return E; */
/* case ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT: return E; */
/* case ERROR_NOLOGON_SERVER_TRUST_ACCOUNT: return E; */
/* case ERROR_NO_LOGON_SERVERS: return E; */
/* case ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT: return E; */
/* case ERROR_NO_MEDIA_IN_DRIVE: return E; */
/* case ERROR_NO_MORE_DEVICES: return E; */
/* case ERROR_NO_MORE_FILES: return E; */
/* case ERROR_NO_MORE_ITEMS: return E; */
/* case ERROR_NO_MORE_SEARCH_HANDLES: return E; */
/* case ERROR_NO_NET_OR_BAD_PATH: return E; */
/* case ERROR_NO_NETWORK: return E; */
/* case ERROR_NO_PROC_SLOTS: return E; */
/* case ERROR_NO_QUOTAS_FOR_ACCOUNT: return E; */
/* case ERROR_NO_SCROLLBARS: return E; */
/* case ERROR_NO_SECURITY_ON_OBJECT: return E; */
/* case ERROR_NO_SHUTDOWN_IN_PROGRESS: return E; */
/* case ERROR_NO_SIGNAL_SENT: return E; */
/* case ERROR_NO_SPOOL_SPACE: return E; */
/* case ERROR_NO_SUCH_ALIAS: return E; */
/* case ERROR_NO_SUCH_DOMAIN: return E; */
/* case ERROR_NO_SUCH_GROUP: return E; */
/* case ERROR_NO_SUCH_LOGON_SESSION: return E; */
/* case ERROR_NO_SUCH_MEMBER: return E; */
/* case ERROR_NO_SUCH_PACKAGE: return E; */
/* case ERROR_NO_SUCH_PRIVILEGE: return E; */
/* case ERROR_NO_SUCH_USER: return E; */
/* case ERROR_NO_SYSTEM_MENU: return E; */
/* case ERROR_NO_SYSTEM_RESOURCES: return E; */
/* case ERROR_NO_TOKEN: return E; */
/* case ERROR_NO_TRUST_LSA_SECRET: return E; */
/* case ERROR_NO_TRUST_SAM_ACCOUNT: return E; */
/* case ERROR_NO_UNICODE_TRANSLATION: return E; */
/* case ERROR_NO_USER_SESSION_KEY: return E; */
/* case ERROR_NO_VOLUME_LABEL: return E; */
/* case ERROR_NO_WILDCARD_CHARACTERS: return E; */
/* case ERROR_NOACCESS: return E; */
/* case ERROR_NON_MDICHILD_WINDOW: return E; */
/* case ERROR_NONE_MAPPED: return E; */
/* case ERROR_NONPAGED_SYSTEM_RESOURCES: return E; */
/* case ERROR_NOT_ALL_ASSIGNED: return E; */
/* case ERROR_NOT_AUTHENTICATED: return E; */
/* case ERROR_NOT_CHILD_WINDOW: return E; */
/* case ERROR_NOT_CONNECTED: return E; */
/* case ERROR_NOT_CONTAINER: return E; */
/* case ERROR_NOT_DOS_DISK: return E; */
 case ERROR_NOT_ENOUGH_MEMORY: return ENOMEM;
/* case ERROR_NOT_ENOUGH_QUOTA: return E; */
/* case ERROR_NOT_ENOUGH_SERVER_MEMORY: return E; */
/* case ERROR_NOT_JOINED: return E; */
/* case ERROR_NOT_LOCKED: return E; */
/* case ERROR_NOT_LOGGED_ON: return E; */
/* case ERROR_NOT_LOGON_PROCESS: return E; */
/* case ERROR_NOT_OWNER: return E; */
/* case ERROR_NOT_READY: return E; */
/* case ERROR_NOT_REGISTRY_FILE: return E; */
/* case ERROR_NOT_SAME_DEVICE: return E; */
/* case ERROR_NOT_SUBSTED: return E; */
/* case ERROR_NOT_SUPPORTED: return E; */
/* case ERROR_NOTIFY_ENUM_DIR: return E; */
/* case ERROR_NT_CROSS_ENCRYPTION_REQUIRED: return E; */
/* case ERROR_NULL_LM_PASSWORD: return E; */
/* case ERROR_OLD_WIN_VERSION: return E; */
/* case ERROR_OPEN_FAILED: return E; */
/* case ERROR_OPEN_FILES: return E; */
/* case ERROR_OPERATION_ABORTED: return E; */
/* case ERROR_OUT_OF_PAPER: return E; */
/* case ERROR_OUT_OF_STRUCTURES: return E; */
/* case ERROR_OUTOFMEMORY: return E; */
/* case ERROR_PAGED_SYSTEM_RESOURCES: return E; */
/* case ERROR_PAGEFILE_QUOTA: return E; */
/* case ERROR_PARTIAL_COPY: return E; */
/* case ERROR_PARTITION_FAILURE: return E; */
/* case ERROR_PASSWORD_EXPIRED: return E; */
/* case ERROR_PASSWORD_MUST_CHANGE: return E; */
/* case ERROR_PASSWORD_RESTRICTION: return E; */
/* case ERROR_PATH_BUSY: return E; */
case ERROR_PATH_NOT_FOUND: return ENOENT;
/* case ERROR_PIPE_BUSY: return E; */
/* case ERROR_PIPE_CONNECTED: return E; */
/* case ERROR_PIPE_LISTENING: return E; */
/* case ERROR_PIPE_NOT_CONNECTED: return E; */
/* case ERROR_POPUP_ALREADY_ACTIVE: return E; */
/* case ERROR_PORT_UNREACHABLE: return E; */
/* case ERROR_POSSIBLE_DEADLOCK: return E; */
/* case ERROR_PRINT_CANCELLED: return E; */
/* case ERROR_PRINT_MONITOR_ALREADY_INSTALLED: return E; */
/* case ERROR_PRINT_MONITOR_IN_USE: return E; */
/* case ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED: return E; */
/* case ERROR_PRINTER_ALREADY_EXISTS: return E; */
/* case ERROR_PRINTER_DELETED: return E; */
/* case ERROR_PRINTER_DRIVER_ALREADY_INSTALLED: return E; */
/* case ERROR_PRINTER_DRIVER_IN_USE: return E; */
/* case ERROR_PRINTER_HAS_JOBS_QUEUED: return E; */
/* case ERROR_PRINTQ_FULL: return E; */
/* case ERROR_PRIVATE_DIALOG_INDEX: return E; */
/* case ERROR_PRIVILEGE_NOT_HELD: return E; */
/* case ERROR_PROC_NOT_FOUND: return E; */
/* case ERROR_PROCESS_ABORTED: return E; */
/* case ERROR_PROTOCOL_UNREACHABLE: return E; */
/* case ERROR_READ_FAULT: return E; */
/* case ERROR_REC_NON_EXISTENT: return E; */
/* case ERROR_REDIR_PAUSED: return E; */
/* case ERROR_REDIRECTOR_HAS_OPEN_HANDLES: return E; */
/* case ERROR_REGISTRY_CORRUPT: return E; */
/* case ERROR_REGISTRY_IO_FAILED: return E; */
/* case ERROR_REGISTRY_RECOVERED: return E; */
/* case ERROR_RELOC_CHAIN_XEEDS_SEGLIM: return E; */
/* case ERROR_REM_NOT_LIST: return E; */
/* case ERROR_REMOTE_SESSION_LIMIT_EXCEEDED: return E; */
/* case ERROR_REQ_NOT_ACCEP: return E; */
/* case ERROR_REQUEST_ABORTED: return E; */
/* case ERROR_RESOURCE_DATA_NOT_FOUND: return E; */
/* case ERROR_RESOURCE_LANG_NOT_FOUND: return E; */
/* case ERROR_RESOURCE_NAME_NOT_FOUND: return E; */
/* case ERROR_RESOURCE_TYPE_NOT_FOUND: return E; */
/* case ERROR_RETRY: return E; */
/* case ERROR_REVISION_MISMATCH: return E; */
/* case ERROR_RING2_STACK_IN_USE: return E; */
/* case ERROR_RING2SEG_MUST_BE_MOVABLE: return E; */
/* case ERROR_RMODE_APP: return E; */
/* case ERROR_RPL_NOT_ALLOWED: return E; */
/* case ERROR_RXACT_COMMIT_FAILURE: return E; */
/* case ERROR_RXACT_INVALID_STATE: return E; */
/* case ERROR_SAME_DRIVE: return E; */
/* case ERROR_SCREEN_ALREADY_LOCKED: return E; */
/* case ERROR_SECRET_TOO_LONG: return E; */
/* case ERROR_SECTOR_NOT_FOUND: return E; */
/* case ERROR_SEEK: return E; */
/* case ERROR_SEEK_ON_DEVICE: return E; */
/* case ERROR_SEM_IS_SET: return E; */
/* case ERROR_SEM_NOT_FOUND: return E; */
/* case ERROR_SEM_OWNER_DIED: return E; */
/* case ERROR_SEM_TIMEOUT: return E; */
/* case ERROR_SEM_USER_LIMIT: return E; */
/* case ERROR_SERIAL_NO_DEVICE: return E; */
/* case ERROR_SERVER_DISABLED: return E; */
/* case ERROR_SERVER_HAS_OPEN_HANDLES: return E; */
/* case ERROR_SERVER_NOT_DISABLED: return E; */
/* case ERROR_SERVICE_ALREADY_RUNNING: return E; */
/* case ERROR_SERVICE_CANNOT_ACCEPT_CTRL: return E; */
/* case ERROR_SERVICE_DATABASE_LOCKED: return E; */
/* case ERROR_SERVICE_DEPENDENCY_DELETED: return E; */
/* case ERROR_SERVICE_DEPENDENCY_FAIL: return E; */
/* case ERROR_SERVICE_DISABLED: return E; */
/* case ERROR_SERVICE_DOES_NOT_EXIST: return E; */
/* case ERROR_SERVICE_EXISTS: return E; */
/* case ERROR_SERVICE_LOGON_FAILED: return E; */
/* case ERROR_SERVICE_MARKED_FOR_DELETE: return E; */
/* case ERROR_SERVICE_NEVER_STARTED: return E; */
/* case ERROR_SERVICE_NO_THREAD: return E; */
/* case ERROR_SERVICE_NOT_ACTIVE: return E; */
/* case ERROR_SERVICE_NOT_FOUND: return E; */
/* case ERROR_SERVICE_REQUEST_TIMEOUT: return E; */
/* case ERROR_SERVICE_SPECIFIC_ERROR: return E; */
/* case ERROR_SERVICE_START_HANG: return E; */
/* case ERROR_SESSION_CREDENTIAL_CONFLICT: return E; */
/* case ERROR_SET_POWER_STATE_FAILED: return E; */
/* case ERROR_SET_POWER_STATE_VETOED: return E; */
/* case ERROR_SETCOUNT_ON_BAD_LB: return E; */
/* case ERROR_SETMARK_DETECTED: return E; */
/* case ERROR_SHARING_BUFFER_EXCEEDED: return E; */
/* case ERROR_SHARING_PAUSED: return E; */
/* case ERROR_SHARING_VIOLATION: return E; */
/* case ERROR_SHUTDOWN_IN_PROGRESS: return E; */
/* case ERROR_SIGNAL_PENDING: return E; */
/* case ERROR_SIGNAL_REFUSED: return E; */
/* case ERROR_SINGLE_INSTANCE_APP: return E; */
/* case ERROR_SOME_NOT_MAPPED: return E; */
/* case ERROR_SPECIAL_ACCOUNT: return E; */
/* case ERROR_SPECIAL_GROUP: return E; */
/* case ERROR_SPECIAL_USER: return E; */
/* case ERROR_SPL_NO_ADDJOB: return E; */
/* case ERROR_SPL_NO_STARTDOC: return E; */
/* case ERROR_SPOOL_FILE_NOT_FOUND: return E; */
/* case ERROR_STACK_OVERFLOW: return E; */
/* case ERROR_STATIC_INIT: return E; */
/* case ERROR_SUBST_TO_JOIN: return E; */
/* case ERROR_SUBST_TO_SUBST: return E; */
/* case ERROR_SUCCESS: return E; */
/* case ERROR_SUCCESS_REBOOT_REQUIRED: return E; */
/* case ERROR_SUCCESS_RESTART_REQUIRED: return E; */
/* case ERROR_SWAPERROR: return E; */
/* case ERROR_SYSTEM_TRACE: return E; */
/* case ERROR_TRANSFORM_NOT_SUPPORTED: return E; */
/* case ERROR_THREAD_1_INACTIVE: return E; */
/* case ERROR_TLW_WITH_WSCHILD: return E; */
/* case ERROR_TOKEN_ALREADY_IN_USE: return E; */
/* case ERROR_TOO_MANY_CMDS: return E; */
/* case ERROR_TOO_MANY_CONTEXT_IDS: return E; */
/* case ERROR_TOO_MANY_LINKS: return E; */
/* case ERROR_TOO_MANY_LUIDS_REQUESTED: return E; */
/* case ERROR_TOO_MANY_MODULES: return E; */
/* case ERROR_TOO_MANY_MUXWAITERS: return E; */
/* case ERROR_TOO_MANY_NAMES: return E; */
/* case ERROR_TOO_MANY_OPEN_FILES: return E; */
/* case ERROR_TOO_MANY_POSTS: return E; */
/* case ERROR_TOO_MANY_SECRETS: return E; */
/* case ERROR_TOO_MANY_SEM_REQUESTS: return E; */
/* case ERROR_TOO_MANY_SEMAPHORES: return E; */
/* case ERROR_TOO_MANY_SESS: return E; */
/* case ERROR_TOO_MANY_SIDS: return E; */
/* case ERROR_TOO_MANY_TCBS: return E; */
/* case ERROR_TRUST_FAILURE: return E; */
/* case ERROR_TRUSTED_DOMAIN_FAILURE: return E; */
/* case ERROR_TRUSTED_RELATIONSHIP_FAILURE: return E; */
/* case ERROR_UNABLE_TO_LOCK_MEDIA: return E; */
/* case ERROR_UNABLE_TO_UNLOAD_MEDIA: return E; */
/* case ERROR_UNEXP_NET_ERR: return E; */
/* case ERROR_UNKNOWN_PORT: return E; */
/* case ERROR_UNKNOWN_PRINT_MONITOR: return E; */
/* case ERROR_UNKNOWN_PRINTPROCESSOR: return E; */
/* case ERROR_UNKNOWN_PRINTER_DRIVER: return E; */
/* case ERROR_UNKNOWN_REVISION: return E; */
/* case ERROR_UNRECOGNIZED_MEDIA: return E; */
/* case ERROR_UNRECOGNIZED_VOLUME: return E; */
/* case ERROR_USER_EXISTS: return E; */
/* case ERROR_USER_MAPPED_FILE: return E; */
/* case ERROR_VC_DISCONNECTED: return E; */
/* case ERROR_WAIT_NO_CHILDREN: return E; */
/* case ERROR_WINDOW_NOT_COMBOBOX: return E; */
/* case ERROR_WINDOW_NOT_DIALOG: return E; */
/* case ERROR_WINDOW_OF_OTHER_THREAD: return E; */
/* case ERROR_WINS_INTERNAL: return E; */
/* case ERROR_WORKING_SET_QUOTA: return E; */
/* case ERROR_WRITE_FAULT: return E; */
/* case ERROR_WRITE_PROTECT: return E; */
/* case ERROR_WRONG_DISK: return E; */
/* case ERROR_WRONG_PASSWORD: return E; */
